### ISSUE TITLE
PowerShell constrained language mode

### ISSUE THREAD

**Issue by MadhuSunke417** [MSEndpointMgr/IntuneDebugToolkit#1]
Seems Some shortcuts are trying to install modules from PSGallery which is **NOT** allowed to install when we enabled PowerShell constrained language mode for regular domain accounts.

**Comment by mmelkersen** [comment]
Hmm MadhuSunke is this a big issue and what do you prefer instead? I can be very time consuming to add all of the modules offline in the package, but I can certainly do that if required.
