### ISSUE TITLE
There is a trojan in your MSI. Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by bgb-wa** [MSEndpointMgr/IntuneDebugToolkit#4]
Trojan:Script/Wacatac.B!ml
This program is dangerous and executes commands from an attacker.
Affected items:
file: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\MSEndpoingMgr\Intune Debug Toolkit\AUTOPILOT Pre-provisioning Readiness (Run as Admin).lnk
startup: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\MSEndpoingMgr\Intune Debug Toolkit\AUTOPILOT Pre-provisioning Readiness (Run as Admin).lnk

**Comment by mmelkersen** [comment]
Hey, no there are no trojans in the lnk files or powershell scripts. 
The new version has been digital signed now. That will help a lot :)

**Comment by bgb-wa** [comment]
[like]  Brian Beaton reacted to your message:
________________________________
